### PR TITLE
adding identifiers

### PR DESCRIPTION
**Pull request by plally**

### CODE REVIEW

**Comment by brandonsturgeon** [comment]
How should we roll this out? We'll need a branch ready on all applicable waiter patron projects

**Comment by brandonsturgeon** [comment]
Is waiter already able to handle this? Also can we resolve conflicts/fix jenkins errs

**Comment by PLally** [comment]
i dont think identifiers have been implemented in waiter yet

**Comment by brandonsturgeon** [comment]
That can be whipped up in an hour or so - this PR still needs to be ready to merge when that happens

**Comment by brandonsturgeon** [comment]
retest this please

**Review by brandonsturgeon — APPROVED** [review]

**Review by brandonsturgeon — APPROVED** [review]

**Pull request merged**
